name       : haskell-half
version    : 0.2.2.3
release    : 3
source     :
    - http://hackage.haskell.org/package/half-0.2.2.3/half-0.2.2.3.tar.gz : 85c244c80d1c889a3d79073a6f5a99d9e769dbe3c574ca11d992b2b4f7599a5c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Half-precision floating-point
description: |
    Half-precision floating-point
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
