name       : haskell-half
version    : '0.3'
release    : 4
source     :
    - https://hackage.haskell.org/package/half-0.3/half-0.3.tar.gz : 06b26fb062a55fa8f5df1cc2fddc47e5303f09977279f05f62d1950a51b72093
license    : BSD-3-Clause
component  : programming.haskell
summary    : Half-precision floating-point
description: |
    Half-precision floating-point
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
