name       : haskell-half
version    : 0.2.2.3
release    : 1
source     :
    - http://hackage.haskell.org/package/half-0.2.2.3/half-0.2.2.3.tar.gz : 85c244c80d1c889a3d79073a6f5a99d9e769dbe3c574ca11d992b2b4f7599a5c
license    : BSD-3-Clause
component  : programming
summary    : Half-precision floating-point
description: |
    Half-precision floating-point
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 half-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/half-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/half-$version/*.a
